upgrade to 1.9.2
-most also update CHANGELOG.md. But when I tried to install I after build I got:
Packages (1) foot-1.9.2-1

Total Installed Size:  0.55 MiB
Net Upgrade Size:      0.03 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                      [######################################################################] 100%
(1/1) checking package integrity                                                                   [######################################################################] 100%
(1/1) loading package files                                                                            [######################################################################] 100%
(1/1) checking for file conflicts                                                                       [######################################################################] 100%
error: failed to commit transaction (conflicting files)
foot: /usr/share/terminfo/f/foot exists in filesystem (owned by foot-terminfo)
foot: /usr/share/terminfo/f/foot-direct exists in filesystem (owned by foot-terminfo)
Errors occurred, no packages were upgraded.